Add V2 Vulnerability Filtering API, fix call to get session metadata
Contrast-Security-OSS/contrast-sdk-java pull request #72
Opened 2021-06-22 18:34 UTC by atzawada

This change implements part of the V2 Application Vulnerability Filtering API, specifically this endpoint:
```
POST  /ng/{orgUuid}/traces/{appId}/filter
```

The other change is to the way the URL is generated for getting the session metadata for an application. Previously the URL would not be generated correctly if the `TraceFilterForm` had no filters or was null.

2021-07-07 17:49 UTC, bryanateoan requested changes
Hi Andy, thank you very much for the contribution.

I have a few request and questions.
1. Remove vscode settings file
2. Questions about re-using TraceFilterForm

2021-07-07 17:49 UTC, bryanateoan commented on .vscode/settings.json
> +{
Please remove this file.

We started adding any IDE specific files into `.gitignore`

2021-07-07 17:49 UTC, bryanateoan commented on src/main/java/com/contrastsecurity/models/TraceFilterBody.java
> +package com.contrastsecurity.models;
Any reason we can't reuse `TraceFilterForm` and just add the missing fields?

2021-07-07 17:49 UTC, bryanateoan commented on src/main/java/com/contrastsecurity/sdk/ContrastSDK.java
> +  /**
If we reuse the `TraceFilterForm` we can also just update the existing `getTraces` method to use V2 vulnerability filtering. Both methods are getting a list of vulnerabilities based on a filter.

2021-07-09 18:34 UTC, atzawada commented
Hi Brian, is there any reason to maintain the fields on the old v2 TraceFilterForm? Are they used to query in a similar fashion anywhere else in the v3 API?

2021-07-12 15:00 UTC, bryanateoan commented
TraceFilterForm is used by `getSessionMetadataForApplicationUrl` and `getTracesByOrganization`. However, similar to getTraces, it is also moving to having its parameters in the body. The `TraceMetadataFilter` can probably be encoded similar to how `appVersionTags` is encoded for the toQuery method.

2021-07-12 15:47 UTC, bryanateoan commented
@atzawada, I'm okay with adding a new getTraces method. Can you mark the existing getTraces that uses the TraceFilterForm as `@Deprecated`.

2021-07-13 14:03 UTC, bryanateoan approved these changes
Thank you very much for the contribution!

2021-07-13 14:04 UTC, merged